services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    container_name: mariadb
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_HOST: ${DB_HOST}
        WP_TITLE: ${WP_TITLE}
        ADM_WP_NAME: ${ADM_WP_NAME}
        ADM_WP_EMAIL: ${ADM_WP_EMAIL}
        WP_USERNAME: ${WP_USERNAME}
        WP_USEREMAIL: ${WP_USEREMAIL}
        WP_HOST: ${WP_HOST}
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password
      - wp_password
      - adm_wp_password
    restart: always

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  
networks:
    inception:
        name: inception
        driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  adm_wp_password:
    file: ../secrets/adm_wp_password.txt
